//
// build.zig
//
// Copyright (C) 2024 Mateusz Stadnik <matgla@live.com>
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General
// Public License along with this program. If not, see
// <https://www.gnu.org/licenses/>.
//

const std = @import("std");
const buildin = @import("builtin");

const toolchain = @import("toolchains").arm_none_eabi_toolchain;

const Config = struct {
    cpu: ?[]const u8 = null,
    build_linker_script_path: ?[]const u8 = null,
    build_bundle_compiler_rt: ?bool = false,
    cpu_clock_frequency_mhz: ?u32 = null,
};

fn load_config(b: *std.Build, config_file: []const u8) !Config {
    const file = try std.fs.cwd().openFile(config_file, .{ .mode = .read_only });
    defer file.close();

    const endPosition = try file.getEndPos();
    const buffer = b.allocator.alloc(u8, endPosition) catch return error.OutOfMemory;
    const readed = try file.read(buffer);
    const parsed = try std.json.parseFromSlice(
        Config,
        b.allocator,
        buffer[0..readed],
        .{
            .ignore_unknown_fields = true,
        },
    );
    return parsed.value;
}

const PllParams = struct {
    vco_freq_hz: u32,
    postdiv1: u32,
    postdiv2: u32,
    actual_freq_khz: u32,
};

/// Find the highest achievable PLL frequency <= requested_mhz.
/// XOSC = 12 MHz, VCO range 750–1600 MHz, postdiv1/2 in [1..7], pd2 <= pd1.
/// Must match the comptime computation in crt.zig exactly.
fn computePllParams(requested_mhz: u32) ?PllParams {
    const xosc_khz: u32 = 12_000;
    const vco_min_khz: u32 = 750_000;
    const vco_max_khz: u32 = 1_600_000;
    const max_khz: u32 = requested_mhz * 1_000;

    var best: PllParams = .{ .vco_freq_hz = 0, .postdiv1 = 0, .postdiv2 = 0, .actual_freq_khz = 0 };

    var fbdiv: u32 = 320;
    while (fbdiv >= 16) : (fbdiv -= 1) {
        const vco_khz = fbdiv * xosc_khz;
        if (vco_khz < vco_min_khz or vco_khz > vco_max_khz) continue;
        var pd1: u32 = 7;
        while (pd1 >= 1) : (pd1 -= 1) {
            var pd2: u32 = pd1;
            while (pd2 >= 1) : (pd2 -= 1) {
                if ((vco_khz % (pd1 * pd2)) != 0) continue;
                const out_khz = vco_khz / (pd1 * pd2);
                if (out_khz > max_khz) continue;
                if (out_khz > best.actual_freq_khz) {
                    best = .{
                        .vco_freq_hz = vco_khz * 1_000,
                        .postdiv1 = pd1,
                        .postdiv2 = pd2,
                        .actual_freq_khz = out_khz,
                    };
                }
            }
        }
    }
    if (best.actual_freq_khz == 0) return null;
    return best;
}

pub fn build(b: *std.Build) !void {
    // build system dependency
    const board = b.option([]const u8, "board", "a board for which the HAL is used") orelse "host";
    const exec_name = b.option([]const u8, "name", "application name for which HAL is used") orelse unreachable;
    const root_file = b.option([]const u8, "root_file", "application root file") orelse unreachable;
    const config_file = b.option([]const u8, "config_file", "path to config.json file generated by KConfig") orelse unreachable;

    const optimize = b.standardOptimizeOption(.{});
    std.log.info("Used board - {s}", .{board});

    const builder = Builder{};
    const hal = try builder.configureBoard(b, @as([]const u8, board), @as([]const u8, exec_name), root_file, optimize, @as([]const u8, config_file));
    const hal_module = b.addModule("hal", .{
        .root_source_file = b.path("hal_import.zig"),
    });
    hal_module.addImport("hal", hal);
}

fn replace_tokens(b: *std.Build, linker_script: []const u8) []u8 {
    const token_position = std.mem.indexOf(u8, linker_script, "${");
    var path: []u8 = b.fmt("{s}", .{linker_script});
    while (token_position) |start_position| {
        const hal_root = b.build_root.path.?;
        const end_position = std.mem.indexOf(u8, path, "}");
        if (end_position) |end| {
            const token = path[start_position + 2 .. end];
            if (std.mem.eql(u8, token, "hal_root")) {
                path = b.fmt("{s}{s}{s}", .{ path[0..start_position], hal_root, path[end + 1 ..] });
            } else {
                unreachable;
            }
        } else {
            return path;
        }
    }
    return path;
}

pub const Builder = struct {
    pub fn configureBoard(_: *const Builder, b: *std.Build, board: []const u8, execName: []const u8, root_file: []const u8, optimize: std.builtin.OptimizeMode, config_file: []const u8) !*std.Build.Module {
        const boardDependency = try std.fmt.allocPrint(b.allocator, "boards/{s}/{s}.zig", .{ board, board });
        defer b.allocator.free(boardDependency);

        const config = try load_config(b, config_file);

        if (config.cpu == null) {
            std.log.err("No CPU entry in config.json", .{});
            unreachable;
        }
        const halDependency = try std.fmt.allocPrint(b.allocator, "mcu/{s}", .{config.cpu.?});
        defer b.allocator.free(halDependency);
        const mcu = b.dependency(halDependency, .{});

        // Propagate clock configuration as C macros for the pico-sdk.
        // Always boot at 150 MHz — the actual overclock is applied later by
        // apply_overclock() after UART init, with proper VREG + QMI setup.
        // We still compute PLL params for the target frequency but only use
        // them in Zig (crt.zig), NOT for runtime_init_clocks().
        if (config.cpu_clock_frequency_mhz) |freq_mhz| {
            if (computePllParams(freq_mhz)) |_| {
                const hal_mod = mcu.module("hal");
                // Force SDK to boot at 150 MHz (stock RP2350 clock)
                const boot_pll = computePllParams(150).?;
                hal_mod.addCMacro("SYS_CLK_KHZ", b.fmt("{d}", .{boot_pll.actual_freq_khz}));
                hal_mod.addCMacro("PLL_SYS_VCO_FREQ_HZ", b.fmt("{d}", .{boot_pll.vco_freq_hz}));
                hal_mod.addCMacro("PLL_SYS_POSTDIV1", b.fmt("{d}", .{boot_pll.postdiv1}));
                hal_mod.addCMacro("PLL_SYS_POSTDIV2", b.fmt("{d}", .{boot_pll.postdiv2}));
            } else {
                std.log.err("Cannot find valid PLL parameters for {d} MHz", .{freq_mhz});
            }
        }

        const root_path = std.Build.LazyPath{ .src_path = .{
            .sub_path = root_file,
            .owner = b,
        } };
        if (mcu.module("hal").resolved_target) |target| {
            const boardModule = b.addModule("board", .{
                .root_source_file = b.path(boardDependency),
                .target = target,
                .optimize = optimize,
            });
            boardModule.addImport("hal", mcu.module("hal"));

            const root_module = b.addModule("root", .{
                .root_source_file = root_path,
                .target = target,
                .optimize = optimize,
            });

            const exe = b.addExecutable(.{
                .name = execName,
                .root_module = root_module,
                // .target = target,
                // .optimize = optimize,
            });
            exe.want_lto = false;
            exe.link_function_sections = true;
            exe.link_data_sections = true;
            exe.link_gc_sections = true;

            exe.use_llvm = true;
            if (config.cpu) |cpu| {
                if (std.mem.eql(u8, cpu, "host")) {
                    exe.linkLibC();
                } else {
                    _ = try toolchain.decorateModuleWithArmToolchain(b, exe.root_module, target);
                }
            }
            exe.root_module.sanitize_c = .trap;
            exe.root_module.addImport("board", boardModule);
            exe.root_module.addImport("hal", mcu.module("hal"));

            const config_zig = b.dupe(config_file);
            const config_without_ext = std.mem.trimEnd(u8, config_zig, ".json");
            const config_zig_ext = try std.mem.concat(b.allocator, u8, &.{ config_without_ext, ".zig" });
            const cwd_path = std.fs.cwd().realpathAlloc(b.allocator, ".") catch |err| {
                return err;
            };
            const hal_path = b.pathJoin(&.{ cwd_path, "hal" });
            const config_zig_relative = std.fs.path.relative(b.allocator, hal_path, config_zig_ext) catch |err| {
                return err;
            };
            const config_module = b.addModule("config", .{
                .root_source_file = b.path(config_zig_relative),
            });
            mcu.module("hal").addImport("config", config_module);
            boardModule.addImport("config", config_module);
            exe.root_module.addImport("config", config_module);

            if (config.build_linker_script_path) |linker_script| {
                const linker = replace_tokens(b, linker_script);
                const path = std.Build.LazyPath{
                    .cwd_relative = linker,
                };
                exe.setLinkerScript(path);
            }

            if (config.build_bundle_compiler_rt) |bundle_compiler_rt| {
                exe.bundle_compiler_rt = bundle_compiler_rt;
            }

            b.installArtifact(exe);
        }
        return mcu.module("hal");
    }
};
