/*
 * output.c
 *
 * The output formats. c-sdk and hex match the SDK's pioasm byte for byte;
 * zig is ours: the same program data as Zig declarations, so a Zig consumer
 * needs no translate-c pass over a generated C header.
 *
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd. (the original pioasm)
 * Copyright (C) 2026 Mateusz Stadnik <matgla@live.com> (the C port)
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "pioasm.h"

#include <stdlib.h>
#include <string.h>

/* The SDK's own formats count as known too, so a .pio file written for it
 * does not warn here about its python or ada blocks. */
int is_known_output_format(const char *lang) {
    static const char *const known[] = {"c-sdk", "python", "hex", "json", "ada", "go", "zig"};
    for (size_t i = 0; i < sizeof(known) / sizeof(known[0]); i++) {
        size_t n = strlen(known[i]);
        if (!strcmp(lang, known[i]) || (!strncmp(lang, known[i], n) && lang[n] == '-')) return 1;
    }
    return 0;
}

static void header(FILE *out, const char *msg) {
    size_t n = strlen(msg);
    fprintf(out, "// ");
    for (size_t i = 0; i < n; i++)
        fputc('-', out);
    fprintf(out, " //\n// %s //\n// ", msg);
    for (size_t i = 0; i < n; i++)
        fputc('-', out);
    fprintf(out, " //\n\n");
}

static int compare_strings(const void *a, const void *b) {
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

/* The code block languages of a program, sorted and unique: the SDK keeps its
 * blocks in a std::map keyed by language. */
static const char **block_languages(Program *p, int *count) {
    const char **langs = xmalloc(sizeof(*langs) * (size_t)(p->code_block_count + 1));
    int n = 0;
    for (int i = 0; i < p->code_block_count; i++)
        langs[n++] = p->code_blocks[i].lang;
    qsort(langs, (size_t)n, sizeof(*langs), compare_strings);
    *count = 0;
    for (int i = 0; i < n; i++)
        if (!*count || strcmp(langs[*count - 1], langs[i])) langs[(*count)++] = langs[i];
    return langs;
}

/* Every language gets a blank line; only `lang`'s blocks are printed. */
static void code_blocks(FILE *out, Program *p, const char *lang) {
    int count;
    const char **langs = block_languages(p, &count);
    for (int i = 0; i < count; i++) {
        fprintf(out, "\n");
        if (strcmp(langs[i], lang)) continue;
        for (int j = 0; j < p->code_block_count; j++) {
            if (strcmp(p->code_blocks[j].lang, lang)) continue;
            fprintf(out, "%s\n", p->code_blocks[j].contents);
        }
    }
    free(langs);
}

static void warn_lang_opts(Assembler *as, const char *format) {
    size_t n = strlen(format);
    for (int i = 0; i < as->program_count; i++) {
        Program *p = as->programs[i];
        for (int j = 0; j < p->lang_opt_count; j++) {
            int seen = 0;
            for (int k = 0; k < j; k++)
                if (!strcmp(p->lang_opts[k].lang, p->lang_opts[j].lang)) seen = 1;
            if (!seen && !strncmp(p->lang_opts[j].lang, format, n))
                fprintf(stderr, "warning: %s does not support output options; %s lang_opt ignored.\n", format,
                        p->lang_opts[j].lang);
        }
    }
}

static const char *const mov_status_names[] = {"STATUS_TX_LESSTHAN", "STATUS_RX_LESSTHAN", "STATUS_IRQ_SET"};

static const char *fifo_join_name(int fifo) {
    switch (fifo) {
    case FIFO_TX: return "PIO_FIFO_JOIN_TX";
    case FIFO_RX: return "PIO_FIFO_JOIN_RX";
    case FIFO_TXPUT: return "PIO_FIFO_JOIN_TXPUT";
    case FIFO_TXGET: return "PIO_FIFO_JOIN_TXGET";
    case FIFO_PUTGET: return "PIO_FIFO_JOIN_PUTGET";
    }
    return NULL;
}

static void instruction_comment(Program *p, int i, char *buf, size_t size) {
    int bits = p->sideset ? p->sideset_bits_including_opt : 0;
    disassemble(buf, size, p->encoded[i], bits, p->sideset ? p->sideset_opt : 0);
}

/* ----- c-sdk ----- */

static void c_symbols(FILE *out, const char *prefix, PublicSymbol *symbols, int count) {
    int n = 0;
    for (int i = 0; i < count; i++) {
        if (symbols[i].is_label) continue;
        fprintf(out, "#define %s%s %d\n", prefix, symbols[i].name, symbols[i].value);
        n++;
    }
    if (n) fprintf(out, "\n");
    n = 0;
    for (int i = 0; i < count; i++) {
        if (!symbols[i].is_label) continue;
        fprintf(out, "#define %soffset_%s %du\n", prefix, symbols[i].name, symbols[i].value);
        n++;
    }
    if (n) fprintf(out, "\n");
}

int output_c_sdk(Assembler *as, FILE *out) {
    PublicSymbol *symbols;
    int count;

    warn_lang_opts(as, "c-sdk");
    header(out, "This file is autogenerated by pioasm; do not edit!");
    fprintf(out, "#pragma once\n\n");
    fprintf(out, "#if !PICO_NO_HARDWARE\n#include \"hardware/pio.h\"\n#endif\n\n");

    symbols = public_symbols(as, as->global, &count);
    c_symbols(out, "", symbols, count);

    for (int i = 0; i < as->program_count; i++) {
        Program *p = as->programs[i];
        const char *prefix = p->name;
        char comment[128];

        header(out, p->name);
        fprintf(out, "#define %s_wrap_target %d\n", prefix, p->final_wrap_target);
        fprintf(out, "#define %s_wrap %d\n", prefix, p->final_wrap);
        fprintf(out, "#define %s_pio_version %d\n", prefix, p->pio_version);
        fprintf(out, "\n");

        symbols = public_symbols(as, p, &count);
        {
            size_t n = strlen(prefix);
            char *full = xmalloc(n + 2);
            memcpy(full, prefix, n);
            full[n] = '_';
            full[n + 1] = 0;
            c_symbols(out, full, symbols, count);
            free(full);
        }

        fprintf(out, "static const uint16_t %s_program_instructions[] = {\n", prefix);
        for (int j = 0; j < p->instruction_count; j++) {
            if (j == p->final_wrap_target) fprintf(out, "            //     .wrap_target\n");
            instruction_comment(p, j, comment, sizeof(comment));
            fprintf(out, "    0x%04x, // %2d: %s\n", (uint16_t)p->encoded[j], j, comment);
            if (j == p->final_wrap) fprintf(out, "            //     .wrap\n");
        }
        fprintf(out, "};\n\n");

        fprintf(out, "#if !PICO_NO_HARDWARE\n");
        fprintf(out, "static const struct pio_program %s_program = {\n", prefix);
        fprintf(out, "    .instructions = %s_program_instructions,\n", prefix);
        fprintf(out, "    .length = %d,\n", p->instruction_count);
        fprintf(out, "    .origin = %d,\n", p->final_origin);
        fprintf(out, "    .pio_version = %s_pio_version,\n", prefix);
        fprintf(out, "#if PICO_PIO_VERSION > 0\n");
        fprintf(out, "    .used_gpio_ranges = 0x%x\n", p->used_gpio_ranges);
        fprintf(out, "#endif\n");
        fprintf(out, "};\n\n");
        fprintf(out, "static inline pio_sm_config %s_program_get_default_config(uint offset) {\n", prefix);
        fprintf(out, "    pio_sm_config c = pio_get_default_sm_config();\n");
        fprintf(out, "    sm_config_set_wrap(&c, offset + %s_wrap_target, offset + %s_wrap);\n", prefix, prefix);
        if (p->in.final_pin_count >= 0) {
            fprintf(out, "    sm_config_set_in_pin_count(&c, %d);\n", p->in.final_pin_count);
            fprintf(out, "    sm_config_set_in_shift(&c, %d, %d, %d);\n", p->in.right, p->in.autop,
                    p->in.final_threshold);
        }
        if (p->out.final_pin_count >= 0) {
            fprintf(out, "    sm_config_set_out_pin_count(&c, %d);\n", p->out.final_pin_count);
            fprintf(out, "    sm_config_set_out_shift(&c, %d, %d, %d);\n", p->out.right, p->out.autop,
                    p->out.final_threshold);
        }
        if (p->final_set_count >= 0) fprintf(out, "    sm_config_set_set_pin_count(&c, %d);\n", p->final_set_count);
        if (p->sideset)
            fprintf(out, "    sm_config_set_sideset(&c, %d, %s, %s);\n", p->sideset_bits_including_opt,
                    p->sideset_opt ? "true" : "false", p->sideset_pindirs ? "true" : "false");
        if (p->mov_status_type != MOV_STATUS_UNSPECIFIED)
            fprintf(out, "    sm_config_set_mov_status(&c, %s, %d);\n", mov_status_names[p->mov_status_type],
                    p->mov_status_final_n);
        if (p->fifo != FIFO_TXRX) fprintf(out, "    sm_config_set_fifo_join(&c, %s);\n", fifo_join_name(p->fifo));
        if (p->clock_div_int != 1 || p->clock_div_frac != 0)
            fprintf(out, "    sm_config_set_clkdiv_int_frac(&c, %u, %u);\n", p->clock_div_int, p->clock_div_frac);
        fprintf(out, "    return c;\n");
        fprintf(out, "}\n");

        code_blocks(out, p, "c-sdk");

        fprintf(out, "#endif\n\n");
    }
    return 0;
}

/* ----- hex ----- */

int output_hex(Assembler *as, FILE *out) {
    if (as->program_count > 1) {
        fprintf(stderr, "error: hex output only supports a single program input\n");
        return 1;
    }
    for (int i = 0; i < as->programs[0]->instruction_count; i++)
        fprintf(out, "%04x\n", as->programs[0]->encoded[i]);
    return 0;
}

/* ----- zig ----- */

static int is_zig_reserved(const char *name) {
    static const char *const words[] = {
        "addrspace", "align", "allowzero", "and", "anyframe", "anytype", "asm", "break", "callconv", "catch",
        "comptime", "const", "continue", "defer", "else", "enum", "errdefer", "error", "export", "extern", "fn",
        "for", "if", "inline", "linksection", "noalias", "noinline", "nosuspend", "opaque", "or", "orelse",
        "packed", "pub", "resume", "return", "struct", "suspend", "switch", "test", "threadlocal", "try",
        "union", "unreachable", "var", "volatile", "while",
        /* primitives: a declaration may not shadow them */
        "anyerror", "anyopaque", "bool", "comptime_float", "comptime_int", "false", "isize", "noreturn", "null",
        "true", "type", "undefined", "usize", "void", "f16", "f32", "f64", "f80", "f128", "c_char", "c_short",
        "c_ushort", "c_int", "c_uint", "c_long", "c_ulong", "c_longlong", "c_ulonglong", "c_longdouble",
    };
    const char *p;
    for (size_t i = 0; i < sizeof(words) / sizeof(words[0]); i++)
        if (!strcmp(name, words[i])) return 1;
    /* i<N> and u<N> integer types */
    if ((name[0] == 'i' || name[0] == 'u') && name[1] >= '0' && name[1] <= '9') {
        for (p = name + 1; *p >= '0' && *p <= '9'; p++)
            ;
        if (!*p) return 1;
    }
    return 0;
}

/* Every declaration name goes through here: `@"x"` when x is reserved. */
static void zig_name(FILE *out, const char *prefix, const char *name) {
    size_t n = strlen(prefix) + strlen(name) + 1;
    char *full = xmalloc(n);
    snprintf(full, n, "%s%s", prefix, name);
    if (is_zig_reserved(full))
        fprintf(out, "@\"%s\"", full);
    else
        fprintf(out, "%s", full);
    free(full);
}

static void zig_symbols(FILE *out, const char *prefix, PublicSymbol *symbols, int count) {
    int n = 0;
    for (int i = 0; i < count; i++) {
        if (symbols[i].is_label) continue;
        fprintf(out, "pub const ");
        zig_name(out, prefix, symbols[i].name);
        fprintf(out, " = %d;\n", symbols[i].value);
        n++;
    }
    if (n) fprintf(out, "\n");
    n = 0;
    for (int i = 0; i < count; i++) {
        if (!symbols[i].is_label) continue;
        fprintf(out, "pub const %soffset_%s = %d;\n", prefix, symbols[i].name, symbols[i].value);
        n++;
    }
    if (n) fprintf(out, "\n");
}

int output_zig(Assembler *as, FILE *out) {
    PublicSymbol *symbols;
    int count;

    warn_lang_opts(as, "zig");
    header(out, "This file is autogenerated by pioasm; do not edit!");
    fprintf(out, "/// Laid out as the Pico SDK's `struct pio_program` (hardware/pio.h), so a\n");
    fprintf(out, "/// pointer to one can be `@ptrCast` to the SDK's type.\n");
    fprintf(out, "pub const Program = extern struct {\n");
    fprintf(out, "    instructions: [*]const u16,\n");
    fprintf(out, "    length: u8,\n");
    fprintf(out, "    origin: i8,\n");
    fprintf(out, "    pio_version: u8,\n");
    fprintf(out, "    used_gpio_ranges: u8,\n");
    fprintf(out, "};\n\n");

    symbols = public_symbols(as, as->global, &count);
    zig_symbols(out, "", symbols, count);

    for (int i = 0; i < as->program_count; i++) {
        Program *p = as->programs[i];
        char *prefix;
        char comment[128];
        size_t n = strlen(p->name);

        prefix = xmalloc(n + 2);
        memcpy(prefix, p->name, n);
        prefix[n] = '_';
        prefix[n + 1] = 0;

        header(out, p->name);
        fprintf(out, "pub const %swrap_target = %d;\n", prefix, p->final_wrap_target);
        fprintf(out, "pub const %swrap = %d;\n", prefix, p->final_wrap);
        fprintf(out, "pub const %spio_version = %d;\n", prefix, p->pio_version);
        fprintf(out, "\n");

        symbols = public_symbols(as, p, &count);
        zig_symbols(out, prefix, symbols, count);

        fprintf(out, "pub const %sprogram_instructions = [_]u16{\n", prefix);
        for (int j = 0; j < p->instruction_count; j++) {
            if (j == p->final_wrap_target) fprintf(out, "    //     .wrap_target\n");
            instruction_comment(p, j, comment, sizeof(comment));
            fprintf(out, "    0x%04x, // %2d: %s\n", (uint16_t)p->encoded[j], j, comment);
            if (j == p->final_wrap) fprintf(out, "    //     .wrap\n");
        }
        fprintf(out, "};\n\n");

        fprintf(out, "pub const %sprogram = Program{\n", prefix);
        fprintf(out, "    .instructions = &%sprogram_instructions,\n", prefix);
        fprintf(out, "    .length = %d,\n", p->instruction_count);
        fprintf(out, "    .origin = %d,\n", p->final_origin);
        fprintf(out, "    .pio_version = %spio_version,\n", prefix);
        fprintf(out, "    .used_gpio_ranges = 0x%x,\n", p->used_gpio_ranges);
        fprintf(out, "};\n\n");

        fprintf(out, "/// `sdk` is the translated hardware/pio.h: pio_get_default_sm_config and the\n");
        fprintf(out, "/// sm_config_set_* calls, as the C header's static inline makes them.\n");
        fprintf(out, "pub fn %sprogram_get_default_config(comptime sdk: type, offset: c_uint) sdk.pio_sm_config {\n",
                prefix);
        fprintf(out, "    var c = sdk.pio_get_default_sm_config();\n");
        fprintf(out, "    sdk.sm_config_set_wrap(&c, offset +%% %swrap_target, offset +%% %swrap);\n", prefix, prefix);
        if (p->in.final_pin_count >= 0) {
            fprintf(out, "    sdk.sm_config_set_in_pin_count(&c, %d);\n", p->in.final_pin_count);
            fprintf(out, "    sdk.sm_config_set_in_shift(&c, %s, %s, %d);\n", p->in.right ? "true" : "false",
                    p->in.autop ? "true" : "false", p->in.final_threshold);
        }
        if (p->out.final_pin_count >= 0) {
            fprintf(out, "    sdk.sm_config_set_out_pin_count(&c, %d);\n", p->out.final_pin_count);
            fprintf(out, "    sdk.sm_config_set_out_shift(&c, %s, %s, %d);\n", p->out.right ? "true" : "false",
                    p->out.autop ? "true" : "false", p->out.final_threshold);
        }
        if (p->final_set_count >= 0)
            fprintf(out, "    sdk.sm_config_set_set_pin_count(&c, %d);\n", p->final_set_count);
        if (p->sideset)
            fprintf(out, "    sdk.sm_config_set_sideset(&c, %d, %s, %s);\n", p->sideset_bits_including_opt,
                    p->sideset_opt ? "true" : "false", p->sideset_pindirs ? "true" : "false");
        if (p->mov_status_type != MOV_STATUS_UNSPECIFIED)
            fprintf(out, "    sdk.sm_config_set_mov_status(&c, sdk.%s, %d);\n", mov_status_names[p->mov_status_type],
                    p->mov_status_final_n);
        if (p->fifo != FIFO_TXRX)
            fprintf(out, "    sdk.sm_config_set_fifo_join(&c, sdk.%s);\n", fifo_join_name(p->fifo));
        if (p->clock_div_int != 1 || p->clock_div_frac != 0)
            fprintf(out, "    sdk.sm_config_set_clkdiv_int_frac(&c, %u, %u);\n", p->clock_div_int,
                    p->clock_div_frac);
        fprintf(out, "    return c;\n");
        fprintf(out, "}\n");

        code_blocks(out, p, "zig");
        fprintf(out, "\n");
        free(prefix);
    }
    return 0;
}
