//
// build.zig
//
// Copyright (C) 2025 Mateusz Stadnik <matgla@live.com>
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, either version
// 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General
// Public License along with this program. If not, see
// <https://www.gnu.org/licenses/>.
//

const std = @import("std");
const builtin = @import("builtin");

const toolchain = @import("toolchains").arm_none_eabi_toolchain;

pub const targetOptions = std.Target.Query{
    .cpu_arch = .thumb,
    .os_tag = .other,
    .abi = .eabihf,
    .cpu_model = .{ .explicit = &std.Target.arm.cpu.cortex_m33 },
    .cpu_features_add = std.Target.arm.featureSet(&[_]std.Target.arm.Feature{
        .fp_armv8d16sp,
    }),
};

pub fn build(b: *std.Build) !void {
    const optimize = b.standardOptimizeOption(.{});
    const target = b.resolveTargetQuery(targetOptions);

    const hal = b.addModule("hal", .{
        .root_source_file = b.path("qemu_mps2.zig"),
        .target = target,
        .optimize = optimize,
    });

    const halInterface = b.dependency("hal_interface", .{ .optimize = optimize, .target = target });
    hal.addImport("hal_interface", halInterface.module("hal_interface"));

    // Minimal CMSIS: generic Core headers + our hand-written MPS2 device header.
    const cmsis = b.addModule("cmsis", .{
        .root_source_file = b.path("cmsis.zig"),
        .target = target,
        .optimize = optimize,
    });
    cmsis.addIncludePath(b.path("../../../libs/pico-sdk/src/rp2_common/cmsis/stub/CMSIS/Core/Include"));
    cmsis.addIncludePath(b.path("device"));

    // Shared cortex-m core (SysTick / NVIC Irq / Registers).
    const cortex_m = b.addModule("cortex-m", .{
        .root_source_file = b.path("../../common/cores/arm/cortex-m/init.zig"),
        .target = target,
        .optimize = optimize,
    });
    cortex_m.addImport("cmsis", cmsis);

    // Shared armv8-m register definitions.
    const arch = b.addModule("arch", .{
        .root_source_file = b.path("../../common/arch/arm/armv8-m/registers.zig"),
        .target = target,
        .optimize = optimize,
    });
    arch.addAssemblyFile(b.path("../../common/arch/arm/armv8-m/irq.S"));
    arch.addImport("hal", hal);
    arch.addImport("cmsis", cmsis);

    hal.addImport("arch", arch);
    hal.addImport("cortex-m", cortex_m);
    cortex_m.addImport("arch", arch);

    _ = try toolchain.decorateModuleWithArmToolchain(b, hal, target);

    const repo_root = try std.Io.Dir.cwd().realPathFileAlloc(b.graph.io, ".", b.allocator);
    hal.addAssemblyFile(b.path("startup/startup.S"));

    const romfs_img_path = try std.fs.path.join(b.allocator, &.{ repo_root, "rootfs.img" });
    const romfs_bytes = std.Io.Dir.cwd().readFileAlloc(b.graph.io, romfs_img_path, b.allocator, .limited(256 * 1024 * 1024)) catch &[_]u8{};
    const romfs_hash = std.hash.Wyhash.hash(0, romfs_bytes);
    const romfs_wf = b.addWriteFiles();
    const rootfs_s = romfs_wf.add("rootfs.S", b.fmt(
        \\// Generated by build.zig — embeds rootfs.img into the .romfs section.
        \\// rootfs.img content hash: 0x{x} (cache-buster; do not edit by hand).
        \\.section .romfs, "a"
        \\.align 4
        \\.global __romfs_blob_start
        \\__romfs_blob_start:
        \\.incbin "rootfs.img"
        \\.global __romfs_blob_end
        \\__romfs_blob_end:
        \\
    , .{romfs_hash}));
    hal.addAssemblyFile(rootfs_s);
    hal.addIncludePath(.{ .cwd_relative = repo_root });
}
