name: Yasos Unit Tests

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  execute_system_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matgla/yasos.zig:v0.15
      credentials: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive' 
      - name: Install zvm 
        shell: bash
        run: 
          curl https://raw.githubusercontent.com/tristanisham/zvm/master/install.sh | bash 
      - name: Fetch packages
        shell: bash
        continue-on-error: true
        run: 
          $HOME/.zvm/self/zvm i 0.14.1 \
          $HOME/.zvm/self/zvm run 0.14.1 build test 
      
      - name: Execute tests 
        shell: bash
        run: 
          zig build test --summary all
