name: Yasos Smoke Tests
on: 
  push: 
    branches: [main]
  pull_request:

jobs:
  smoke_tests:
    runs-on: [self-hosted, pimoroni_pico_plus2]
    steps:
      - name: Cleanup workspace 
        run: |
          rm -rf "$GITHUB_WORKSPACE" 
          mkdir -p "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
        with: 
          submodules: 'recursive'
      - name: Run Smoke Tests
        run: |
          make run_smoke_tests
      
      - name: Upload Test Logs  
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke_test_logs
          path: ${{ github.workspace }}/tests/smoke/logs/*