name: Yasos Smoke Tests
on: 
  push: 
    branches: [main]
  pull_request:

jobs:
  smoke_tests:
    runs-on: [self-hosted, pimoroni_pico_plus2]
    - name: Build yasos
      run: |
        zig build -Doptimize=ReleaseFast
    - name: Build rootfs
      run: |
        ./build_rootfs.sh -c -o rootfs.img
    - name: Prepare environment
      run: |
        ./tests/smoke/prepare.sh

    - name: Run smoke tests
      run: |
        ./tests/smoke/run_tests.sh
